-- USER SQL
CREATE USER NatCrooker IDENTIFIED BY NatCrooker2017
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER NatCrooker QUOTA 1024000M ON USERS;

-- ROLES
GRANT "CONNECT" TO NatCrooker;

-- SYSTEM PRIVILEGES
GRANT DROP ANY TRIGGER TO NatCrooker;
GRANT ALTER ANY INDEX TO NatCrooker;
GRANT DROP ANY SEQUENCE TO NatCrooker;
GRANT UNDER ANY TABLE TO NatCrooker;
GRANT CREATE TRIGGER TO NatCrooker;
GRANT ALTER ANY PROCEDURE TO NatCrooker;
GRANT ADMINISTER DATABASE TRIGGER TO NatCrooker;
GRANT MERGE ANY VIEW TO NatCrooker;
GRANT CREATE ANY INDEX TO NatCrooker;
GRANT ALTER ANY MATERIALIZED VIEW TO NatCrooker;
GRANT DEBUG ANY PROCEDURE TO NatCrooker;
GRANT CREATE ANY SEQUENCE TO NatCrooker;
GRANT CREATE VIEW TO NatCrooker;
GRANT ALTER ANY TABLE TO NatCrooker;
GRANT CREATE
  RULE TO NatCrooker;
GRANT SELECT ANY TABLE TO NatCrooker;
GRANT FORCE ANY TRANSACTION TO NatCrooker;
GRANT DELETE ANY TABLE TO NatCrooker;
GRANT ALTER ANY SEQUENCE TO NatCrooker;
GRANT DROP ANY MATERIALIZED VIEW TO NatCrooker;
GRANT BACKUP ANY TABLE TO NatCrooker;
GRANT CREATE TABLE TO NatCrooker;
GRANT DROP ANY TABLE TO NatCrooker;
GRANT DROP
  ANY RULE TO NatCrooker;
GRANT CREATE
  ANY RULE TO NatCrooker;
GRANT EXECUTE ANY PROCEDURE TO NatCrooker;
GRANT CREATE SEQUENCE TO NatCrooker;
GRANT DROP ANY INDEX TO NatCrooker;
GRANT UPDATE ANY TABLE TO NatCrooker;
GRANT DROP ANY VIEW TO NatCrooker;
GRANT EXECUTE ANY RULE TO NatCrooker;
GRANT UNDER ANY VIEW TO NatCrooker;
GRANT ALTER ANY TRIGGER TO NatCrooker;
GRANT CREATE ANY VIEW TO NatCrooker;
GRANT EXPORT
  FULL DATABASE TO NatCrooker;
GRANT IMPORT
  FULL DATABASE TO NatCrooker;
GRANT COMMENT ANY TABLE TO NatCrooker;
GRANT INSERT ANY TABLE TO NatCrooker;
GRANT CREATE ANY MATERIALIZED VIEW TO NatCrooker;
GRANT FORCE TRANSACTION TO NatCrooker;
GRANT DROP ANY PROCEDURE TO NatCrooker;
GRANT CREATE ANY TRIGGER TO NatCrooker;
GRANT CREATE ANY TABLE TO NatCrooker;
GRANT CREATE PROCEDURE TO NatCrooker;
GRANT ALTER ANY RULE TO NatCrooker;

